/**
 * @fileoverview gRPC-Web generated client stub for stock_exchange
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: stock.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as stock_pb from './stock_pb'; // proto import: "stock.proto"


export class StockExchangeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSubscribeQuotes = new grpcWeb.MethodDescriptor(
    '/stock_exchange.StockExchange/SubscribeQuotes',
    grpcWeb.MethodType.SERVER_STREAMING,
    stock_pb.QuoteSubscription,
    stock_pb.StockQuote,
    (request: stock_pb.QuoteSubscription) => {
      return request.serializeBinary();
    },
    stock_pb.StockQuote.deserializeBinary
  );

  subscribeQuotes(
    request: stock_pb.QuoteSubscription,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<stock_pb.StockQuote> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/stock_exchange.StockExchange/SubscribeQuotes',
      request,
      metadata || {},
      this.methodDescriptorSubscribeQuotes);
  }

  methodDescriptorPlaceOrder = new grpcWeb.MethodDescriptor(
    '/stock_exchange.StockExchange/PlaceOrder',
    grpcWeb.MethodType.UNARY,
    stock_pb.OrderRequest,
    stock_pb.OrderResponse,
    (request: stock_pb.OrderRequest) => {
      return request.serializeBinary();
    },
    stock_pb.OrderResponse.deserializeBinary
  );

  placeOrder(
    request: stock_pb.OrderRequest,
    metadata?: grpcWeb.Metadata | null): Promise<stock_pb.OrderResponse>;

  placeOrder(
    request: stock_pb.OrderRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: stock_pb.OrderResponse) => void): grpcWeb.ClientReadableStream<stock_pb.OrderResponse>;

  placeOrder(
    request: stock_pb.OrderRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: stock_pb.OrderResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/stock_exchange.StockExchange/PlaceOrder',
        request,
        metadata || {},
        this.methodDescriptorPlaceOrder,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/stock_exchange.StockExchange/PlaceOrder',
    request,
    metadata || {},
    this.methodDescriptorPlaceOrder);
  }

  methodDescriptorCancelOrder = new grpcWeb.MethodDescriptor(
    '/stock_exchange.StockExchange/CancelOrder',
    grpcWeb.MethodType.UNARY,
    stock_pb.CancelOrderRequest,
    stock_pb.CancelOrderResponse,
    (request: stock_pb.CancelOrderRequest) => {
      return request.serializeBinary();
    },
    stock_pb.CancelOrderResponse.deserializeBinary
  );

  cancelOrder(
    request: stock_pb.CancelOrderRequest,
    metadata?: grpcWeb.Metadata | null): Promise<stock_pb.CancelOrderResponse>;

  cancelOrder(
    request: stock_pb.CancelOrderRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: stock_pb.CancelOrderResponse) => void): grpcWeb.ClientReadableStream<stock_pb.CancelOrderResponse>;

  cancelOrder(
    request: stock_pb.CancelOrderRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: stock_pb.CancelOrderResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/stock_exchange.StockExchange/CancelOrder',
        request,
        metadata || {},
        this.methodDescriptorCancelOrder,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/stock_exchange.StockExchange/CancelOrder',
    request,
    metadata || {},
    this.methodDescriptorCancelOrder);
  }

  methodDescriptorGetOrderHistory = new grpcWeb.MethodDescriptor(
    '/stock_exchange.StockExchange/GetOrderHistory',
    grpcWeb.MethodType.UNARY,
    stock_pb.OrderHistoryRequest,
    stock_pb.OrderHistoryResponse,
    (request: stock_pb.OrderHistoryRequest) => {
      return request.serializeBinary();
    },
    stock_pb.OrderHistoryResponse.deserializeBinary
  );

  getOrderHistory(
    request: stock_pb.OrderHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<stock_pb.OrderHistoryResponse>;

  getOrderHistory(
    request: stock_pb.OrderHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: stock_pb.OrderHistoryResponse) => void): grpcWeb.ClientReadableStream<stock_pb.OrderHistoryResponse>;

  getOrderHistory(
    request: stock_pb.OrderHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: stock_pb.OrderHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/stock_exchange.StockExchange/GetOrderHistory',
        request,
        metadata || {},
        this.methodDescriptorGetOrderHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/stock_exchange.StockExchange/GetOrderHistory',
    request,
    metadata || {},
    this.methodDescriptorGetOrderHistory);
  }

  methodDescriptorGetPortfolio = new grpcWeb.MethodDescriptor(
    '/stock_exchange.StockExchange/GetPortfolio',
    grpcWeb.MethodType.UNARY,
    stock_pb.PortfolioRequest,
    stock_pb.PortfolioResponse,
    (request: stock_pb.PortfolioRequest) => {
      return request.serializeBinary();
    },
    stock_pb.PortfolioResponse.deserializeBinary
  );

  getPortfolio(
    request: stock_pb.PortfolioRequest,
    metadata?: grpcWeb.Metadata | null): Promise<stock_pb.PortfolioResponse>;

  getPortfolio(
    request: stock_pb.PortfolioRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: stock_pb.PortfolioResponse) => void): grpcWeb.ClientReadableStream<stock_pb.PortfolioResponse>;

  getPortfolio(
    request: stock_pb.PortfolioRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: stock_pb.PortfolioResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/stock_exchange.StockExchange/GetPortfolio',
        request,
        metadata || {},
        this.methodDescriptorGetPortfolio,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/stock_exchange.StockExchange/GetPortfolio',
    request,
    metadata || {},
    this.methodDescriptorGetPortfolio);
  }

}

export class MarketDataClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamMarketData = new grpcWeb.MethodDescriptor(
    '/stock_exchange.MarketData/StreamMarketData',
    grpcWeb.MethodType.SERVER_STREAMING,
    stock_pb.MarketDataRequest,
    stock_pb.MarketDataUpdate,
    (request: stock_pb.MarketDataRequest) => {
      return request.serializeBinary();
    },
    stock_pb.MarketDataUpdate.deserializeBinary
  );

  streamMarketData(
    request: stock_pb.MarketDataRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<stock_pb.MarketDataUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/stock_exchange.MarketData/StreamMarketData',
      request,
      metadata || {},
      this.methodDescriptorStreamMarketData);
  }

}

